
services:
  - type: web
    name: pdf2word-vietnamese
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    branch: main
    autoDeploy: true
