services:
  - type: web
    name: pdf-to-word-converter
    env: python
    buildCommand: ./build.sh && pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    autoDeploy: true
